project_id = "syflufvohjamjngttugh"

[functions.subscribe-newsletter]
verify_jwt = false

[functions.notify-new-subscriber]
verify_jwt = false

[functions.sync-subscriber-webhook]
verify_jwt = false

[functions.sync-contact-webhook]
verify_jwt = false
